TECH-114: Create feature implementation for Cucumber tests for database list and database schema read
GovStackWorkingGroup/bb-digital-registries pull request #15
Opened 2023-01-02 16:18 UTC by mgrochalskisoldevelo

Create feature implementation for Cucumber tests for database list and database schema read

## Description
For database list and database schema read features file created, implement the Cucumber features using javascript. 
Create all necessary code to implement the test that have been defined. Store the files in /tests/features/support.

TICKET https://govstack-global.atlassian.net/browse/TECH-114

2023-01-03 10:34 UTC, KarolinaKopacz requested changes

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +  specDataRead.response().should.have.status(200);
In the titile is "The user received a list of..." - is it possible to check if user really receive those list? What is API response?

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +  specDataRead.response().should.have.status(400);
Is the response from API empty or there is some json or string ? If yes, check if those response is what you expect :)

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +  specDataRead.response().should.have.status(400);
The same what above

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +const pactum = require('pactum');
There is no `db_datasets.feature` file so please change the name of file to the `db_list.js`

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +  specDataRead.response().should.have.status(200);
Is the response from API empty or there is some json or string ? If yes, check if those response is what you expect :)

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +  specDataRead.response().should.have.status(400);
Is the response from API empty or there is some json or string ? If yes, check if those response is what you expect :)

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +  specDataRead.response().should.have.status(400);
Is the response from API empty or there is some json or string ? If yes, check if those response is what you expect :)

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +    specDataRead.response().should.have.status(400);
Is the response from API empty or there is some json or string ? If yes, check if those response is what you expect :)

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/package.json
> +    "@cucumber/cucumber": "^8.10.0",
Is it necessary?

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +      .get(`${baseUrl}`)
```suggestion
      .get(baseUrl)
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +      .get(`${baseUrl}`)
```suggestion
      .get(baseUrl)
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +    .get(`${baseUrl}`);
```suggestion
    .get(baseUrl);
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +  specDataRead = pactum.spec();
```suggestion
  specDatabaseRead = pactum.spec();
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +      .get(`${baseUrl}`)
```suggestion
      .get(baseUrl)
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +      .get(`${baseUrl}`)
```suggestion
      .get(baseUrl)
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +    .get(`${baseUrl}`);
```suggestion
    .get(baseUrl);
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_read.js
> +      .get(`${baseUrl}`);
```suggestion
      .get(baseUrl);
```

2023-01-03 10:34 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_datasets.js
> +  specDataRead = pactum.spec();
```suggestion
  specDatabaseList = pactum.spec();
```

2023-01-04 12:44 UTC, KarolinaKopacz commented on test/gerkin/features/db_list.feature
> +      Then The operation of receiving information about the databases of Digital Registers results with an error of the invalid header
```suggestion
      The result of an operation to receive information about the databases of Digital Registers returns an error
```

2023-01-04 12:44 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_list.js
> +let specDatabaseRead;
```suggestion
let specDatabaseList;
```

2023-01-04 12:44 UTC, KarolinaKopacz commented on test/gerkin/features/steps/db_list.js
> +  specDatabaseRead = pactum.spec();
```suggestion
  specDatabaseList = pactum.spec();
```

2023-01-04 12:45 UTC, KarolinaKopacz commented
Great! You added a lot of changes.

2023-01-05 02:25 UTC, conradsp approved these changes

2023-01-05 07:46 UTC, KarolinaKopacz approved these changes

2023-01-05 10:22 UTC, dborowiecki approved these changes

2023-01-05 11:05 UTC, merged