TECH-464: Update GET /databases
GovStackWorkingGroup/bb-digital-registries pull request #25
Opened 2023-03-22 15:30 UTC by KarolinaKopacz

Update GET /databases.
Need to update every tests in bb-digital-registry. Make sure tests contain are similar with https://govstack-global.atlassian.net/wiki/spaces/GH/pages/157712385/Gherkin+file+template

2023-03-24 06:51 UTC, ingmarvali approved these changes

2023-03-27 08:29 UTC, mgrochalskisoldevelo requested changes

2023-03-27 08:29 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/db_list.js
> +  async () =>
```suggestion
  () =>
```

2023-03-27 08:29 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/db_list.js
> +Then('The \\/databases endpoint response should have status 200', async () =>
```suggestion
Then('The \\/databases endpoint response should have status 200', () =>
```

2023-03-27 08:29 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/db_list.js
> +  async () =>
```suggestion
  () =>
```

2023-03-27 08:29 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/db_list.js
> +Then('The \\/databases endpoint response should match json schema', async () =>
```suggestion
Then('The \\/databases endpoint response should match json schema', () =>
```

2023-03-27 09:30 UTC, mgrochalskisoldevelo approved these changes

2023-03-27 09:30 UTC, merged