TECH-467: Update Cucumber Test POST: /data/registryname/versionnumber…
GovStackWorkingGroup/bb-digital-registries pull request #32
Opened 2023-04-20 07:08 UTC by mdulko

### **Description**
Update cucumber test for POST /data/<registryname>/<versionnumber>/exists
Make sure tests contain

- smoke tests
- sanity performance tests
- no hard-coded data
- header tests
- etc. that are described in https://govstack-global.atlassian.net/wiki/spaces/GH/pages/157712385/Gherkin+file+template
- API spec: https://github.com/GovStackWorkingGroup/bb-payments/blob/main/api/UpdateBeneficiary.yaml

Acceptance criteria:

- test is updated
- test match with accepted template

Ticket: https://govstack-global.atlassian.net/browse/TECH-467

2023-04-20 11:22 UTC, mgrochalskisoldevelo requested changes

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    When POST request with given path params "registryname" as registryname and "111" as versionnumber
specify what is called. we can repeat it in .feature file, but if we do so repeating code for it in .js file will compile with errors.
So better make the text more unique

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    When POST request with given path params "registryname" as registryname and "111" as versionnumber
+ for each given when then it works like that

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    Scenario: Successfully receives a message that the record exists in database
```suggestion
    Scenario: Successfully receives a message that the record exists in database smoke type test
```

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    Scenario: Successfully receive status value true for existing record
```suggestion
    Scenario: Successfully receives a message that the record exists in database
```

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/data_exist.js
>        .withBody({
```suggestion
      .withJson({
```

2023-04-20 11:22 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/data_exist.js
> +Then(
missing scenario description above + comment about others given,when,then

2023-04-20 20:09 UTC, mgrochalskisoldevelo requested changes

2023-04-20 20:09 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    Scenario: Successfully receives a message that the record not exists in database
This scenario could be negative regression unit test.
Please add **Examples** data table and provide more examples. I guess we can use different name only, the rest could stay the same

2023-04-20 20:09 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_exist.feature
> +    Scenario: Successfully receives a message that the record exists in database
This test checks basically the same things as smoke test. I propose to add @unit and @positive tags to unit test.
Also add last And step to smoke test and remove the scenario

2023-04-24 09:37 UTC, KarolinaKopacz approved these changes

2023-04-24 13:11 UTC, mgrochalskisoldevelo approved these changes
lgtm

2023-04-27 13:48 UTC, merged