TECH-474: Update BB Digital Registry - GET /data/MyPersonalDataUsage/1.0
GovStackWorkingGroup/bb-digital-registries pull request #33
Opened 2023-04-20 14:05 UTC by KarolinaKopacz

Update BB Digital Registry - GET /data/MyPersonalDataUsage/1.0

Ticket: https://govstack-global.atlassian.net/browse/TECH-474

2023-04-20 20:30 UTC, mgrochalskisoldevelo requested changes
A few small comments from me. Also I think you missed one response 
![image](https://user-images.githubusercontent.com/119664031/233480906-05bfa268-7a9a-45c3-8b22-0e43350beeee.png)

2023-04-20 20:30 UTC, mgrochalskisoldevelo commented on examples/mock/mockoon-digitalregistries.json
> +          "body": "[\n  {\n    \"ID\": \"1234567\",\n    \"ReaderID\": \"{{queryParam 'userID'}}\",\n    \"ReaderInitials\": \"JD\",\n    \"ReaderInstitutionID\": \"EE70049837\",\n    \"ReaderInstitu
I think 
```
ReaderID
```
won't be the same as this one from the request. 

Request -> User's personal unique identifier (User that wants to see who has read his personal data)
Response -> Identifier of a reader who looked at personal data

2023-04-20 20:30 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_my_personal_data_usage.feature
> +  Scenario: The user gets a list of all records that have read their personal data smoke test type
```suggestion
  Scenario: The user gets a list of all records that have read his personal data smoke test type
```

2023-04-20 20:30 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_my_personal_data_usage.feature
> +  Scenario Outline: The user gets a list of all records that have read their personal data
```suggestion
  Scenario Outline: The user gets a list of all records that have read his personal data
```

2023-04-20 20:30 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/data_my_personal_data_usage.js
>    specDataMyPersonalDataUsage = pactum.spec();
```suggestion
  specDataMyPersonalDataUsage = spec();
```

2023-04-20 20:30 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/data_my_personal_data_usage.js
> +let returnedReferanceArray;
seems like this is not used

2023-04-24 09:18 UTC, mgrochalskisoldevelo approved these changes
lgtm

2023-05-08 18:28 UTC, ingmarvali approved these changes

2023-05-09 06:58 UTC, merged

2023-05-09 07:09 UTC, mdulko commented
lgtm