TECH-469: Update cucumber test for PUT /data/registryname/versionnumber/update
GovStackWorkingGroup/bb-digital-registries pull request #34
Opened 2023-04-23 22:58 UTC by mdulko

### **Description**
Update cucumber test for PUT /data/registryname/versionnumber/update
Make sure tests contain

- smoke tests
- sanity performance tests
- no hard-coded data
- header tests
- etc. that are described in https://govstack-global.atlassian.net/wiki/spaces/GH/pages/157712385/Gherkin+file+template
- API spec: https://github.com/GovStackWorkingGroup/bb-payments/blob/main/api/UpdateBeneficiary.yaml

Acceptance criteria:

- test is updated
- test match with accepted template

Ticket: https://govstack-global.atlassian.net/browse/TECH-469

2023-04-25 09:49 UTC, mgrochalskisoldevelo requested changes
Also there is something wrong in the mockoon. To test it set a new response with the status code 400, after this one with status code 200. And set 400 as the default one. If tests will return 200 everything is okay, if 400 there is something to fix in the `Rules`. Remove the 400 status code response after

2023-04-25 09:49 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    And the response from /data/{registryname}/{versionnumber}/update should match json schema
![image](https://user-images.githubusercontent.com/119664031/234238325-f160e0ff-6bdf-44a3-b6f6-5eae5454010b.png)

2023-04-25 09:49 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    Scenario: Successfully update user information record in database smoke type test
smoke should also take all params required for "query" and "write" in the payload

2023-04-25 09:49 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    And the request contains a payload with given "EE378627348834" as ID "John" as FirstName "Helmut" as LastName and "RR-1234567889" as BirthCertificateID and the request overwrites the record with
Use examples table for it with let's say 3 examples

2023-04-25 10:43 UTC, KarolinaKopacz approved these changes

2023-04-25 10:47 UTC, mgrochalskisoldevelo requested changes

2023-04-25 10:47 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +      | EE378627348833 | Jack | Black | RR-1234567880 |
I believe that id should be the same and does not change after update

2023-04-25 10:47 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    Scenario: Successfully update user information record in database smoke type test
```suggestion
    Scenario: Successfully updates user information record in the database smoke type test
```

2023-04-25 10:47 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    When PUT request to check if the record exists in the database is sent with given path params "registryname" as registryname and "111" as versionnumber
you don't check if the record exists, but tries to update it

2023-04-25 10:47 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/helpers/helpers.js
> +  write: {
write is also marked as required in the api spec, please add it here

2023-04-25 10:47 UTC, mgrochalskisoldevelo commented on test/openAPI/features/data_update.feature
> +    And the request contains a payload with given "EE378627348834" as ID "John" as FirstName "Helmut" as LastName and "RR-1234567889" as BirthCertificateID and the request overwrites the record with
in examples it can stay like it is

2023-04-25 13:18 UTC, KarolinaKopacz approved these changes

2023-04-27 12:48 UTC, ingmarvali approved these changes

2023-04-27 14:47 UTC, merged