Feature/tech 714: setup of openIMIS as an example application
GovStackWorkingGroup/bb-digital-registries pull request #42
Opened 2023-06-13 14:48 UTC by lruzicki

Ticket:
https://govstack-global.atlassian.net/browse/TECH-714

Changes:
- added openIMIS as an example application

Notes:
- locally test are running against openIMIS. However, an adaptor has not been created yet. As a result, 58 tests will fail. The main goal at this stage is to ensure that the test harness recognizes openIMIS as a valid test candidate and runs tests against it.

2023-06-14 12:19 UTC, ingmarvali approved these changes

2023-06-15 10:44 UTC, dborowiecki requested changes
I left some general comments. Please switch database from MSQL to PSQL, as in future we want to fully migrate.

2023-06-15 10:44 UTC, dborowiecki commented on examples/openIMIS/.env
> +PROJECT_NAME=openimis
We can use custom project name like digitalRegistryOpenIMIS

2023-06-15 10:44 UTC, dborowiecki commented on examples/openIMIS/docker-compose.yml
> +      context: https://github.com/openimis/openimis-be_py.git#Test_Harness_Setup
I'd also change this branch name. Test_Harness_Setup is too generic, we should go for something related to GovStack. Also it's we shouldn't use snake_case in this context. It's suggested to use kebab-case/and-slashes for naming branches.

2023-06-15 10:44 UTC, dborowiecki commented on examples/openIMIS/test_entrypoint.sh
> +docker-compose exec backend chmod +x /openimis-be/openIMIS/custom_scripts/check_service_availability.sh
you can copy `check_service_availability.sh` script to main folder instead of openIMIS to simplify path

2023-06-15 10:44 UTC, dborowiecki commented on examples/openIMIS/docker-compose.yml
> +      - photos:/openimis-be/openIMIS/images/insurees
Test's build should be ephemeral. I think we don't need to create any volumes in GovStack test execution.

2023-06-15 10:44 UTC, dborowiecki commented on examples/openIMIS/docker-compose.yml
> +      - ./check_service_availability.sh:/openimis-be/openIMIS/custom_scripts/check_service_availability.sh
Importing it to the server through volume seems a bit hacky. In the long term we could think about custom backend Dockerfile used exclusively by GovStack test harness, but for the time being we can keep it in current form. If we'll need to have more contributions from example/openIMIS to container, we will need to switch for Dockerfile.

2023-06-16 12:05 UTC, dborowiecki approved these changes

2023-06-16 12:05 UTC, merged