TECH-122: Generic mockoon api added
GovStackWorkingGroup/bb-digital-registries pull request #8
Opened 2022-12-22 11:10 UTC by dborowiecki

Ticket: [TECH-122](https://govstack-global.atlassian.net/browse/TECH-122)
## Description
This contribution provides proof of concept for generic Mockoon API example created from OpenAPI schema. 
Dockerized application gathers all .yaml files from /api subdirectory, and creates single schema used by mockoon-cli. Pasting example/mockoon into other building blocks should work without additional configuration changes.

2022-12-22 11:37 UTC, KarolinaKopacz approved these changes

2022-12-22 12:53 UTC, dszafranek requested changes

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +const assemblyApiFileName = 'AssemblyApiDefinition.yaml'
```suggestion
const assemblyApiFileName = 'AssemblyApiDefinition.yaml';
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +    validateUnique(existingObj[property], newObj[property], property)
```suggestion
    validateUnique(existingObj[property], newObj[property], property);
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +        existingObj[property] = {...existingObj[property], ...newObj[property]}
```suggestion
        existingObj[property] = {...existingObj[property], ...newObj[property]};
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +    const filePath = path.join(directoryPath, assemblyApiFileName)
```suggestion
    const filePath = path.join(directoryPath, assemblyApiFileName);
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +    let fileArray = []
```suggestion
    let fileArray = [];
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +    let assembly =    {
```suggestion
    let assembly = {
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                const apiDir = path.join(directoryPath, file)
```suggestion
                const apiDir = path.join(directoryPath, file);
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                const nextYAML = yaml.load(fs.readFileSync(apiDir, 'utf8'))
```suggestion
                const nextYAML = yaml.load(fs.readFileSync(apiDir, 'utf8'));
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                extendObjectProperty(assembly, nextYAML, 'paths')
```suggestion
                extendObjectProperty(assembly, nextYAML, 'paths');
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                extendObjectProperty(assembly.components, nextYAML.components, 'schemas')
```suggestion
                extendObjectProperty(assembly.components, nextYAML.components, 'schemas');
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                extendObjectProperty(assembly.components, nextYAML.components, 'parameters')
```suggestion
                extendObjectProperty(assembly.components, nextYAML.components, 'parameters');
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                extendObjectProperty(assembly.components, nextYAML.components, 'securitySchemes')
```suggestion
                extendObjectProperty(assembly.components, nextYAML.components, 'securitySchemes');
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +                console.warn("Found non YAML file in api directory. It'll not used in API definiion. [%s]", file)
```suggestion
                console.warn("Found non YAML file in API directory. It'll not used in API definition. [%s]", file);
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +        saveApiDefinition(assembly)
```suggestion
        saveApiDefinition(assembly);
```

2022-12-22 12:53 UTC, dszafranek commented on examples/mockoon/api_organizer.js
> +loadApiYAMLs()
```suggestion
loadApiYAMLs();
```

2022-12-22 15:17 UTC, dborowiecki commented
@dszafranek Thanks for detailed review. There were multiple issues related to styles, to avoid that in the future I've attached eslint to the project.

2022-12-23 09:03 UTC, dszafranek approved these changes

2022-12-23 09:04 UTC, merged